### ISSUE TITLE
Blank space on many pages

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-archive/TCO21-Regionals-QA-Competition#4]
### Target URL
https://www.newegg.com/
https://www.newegg.com/p/N82E16868110294?IsFeedbackTab=true&Item=9SIAN2HF047639&cm_sp=Homepage_BS-_-P1_9SIAN2HF047639-_-08042021#scrollFullInfo
![PlayStation PS5 Console - Newegg com - Google Chro](https://user-images.githubusercontent.com/42939505/128184408-dbdf2530-4b5c-424c-a359-df7f9c079170.png)

### Steps to Reproduce

1. Open the URL https://www.newegg.com/
2. Scroll down at the bottom
3. Observe there is a lot of space
4. And it's on most of the pages

### Actual Result(s)
There is a lot of blank space 

### Expected Result(s)
There should not be these much of blank space

### Environment Details
Device(s): HP
Operating System: Window 10
Browser(s): Chrome Version 92.0.4515.131 (Official Build) (64-bit)
![Screenshot 2021-08-04 181450](https://user-images.githubusercontent.com/42939505/128183587-9f13e48f-df2d-4cc5-bb96-669e66039b5b.png)

**Comment by swap12875** [comment]
the Target Url shared in the bug report is directing to the product 'PlayStation PS5 Console' where no blank space is visible on the page , please refer below snap 
![image](https://user-images.githubusercontent.com/67191980/128232279-35bc8199-8f16-4e96-95d9-3582afd1bfa6.png)
Also the other screen shot shared in the bug report has no Url mentioned on the report for verification.

**Comment by codejamtc** [comment]
I assume this is due to an ad-blocker in your system. The advert is not visible in your system hence the blank area is visible

![bandicam 2021-08-05 18-46-38-936](https://user-images.githubusercontent.com/42398485/128356457-e60448e2-b500-432c-8096-658a64089c2b.jpg)

![bandicam 2021-08-05 18-49-46-130](https://user-images.githubusercontent.com/42398485/128356785-bdf52f5e-c0d2-477c-a747-80149dbb192f.jpg)


**Submitter** = 0 Points
**Challenger** = 0 Points (Direct URL spacing Issue - bandicam 2021-08-05 18-46-38-936; If we follow the steps bandicam 2021-08-05 18-49-46-130) Challenger's screenshot location is incorrect and challenge label is incorrect. Suites ` Challenge {No Repro}`
